.ALIASES
V_V1            V1(+=A -=0 ) CN @TEST.SCHEMATIC1(sch_1):I00044@SOURCE.VDC.Normal(chips)
V_V2            V2(+=N00212 -=0 ) CN @TEST.SCHEMATIC1(sch_1):I00068@SOURCE.VDC.Normal(chips)
R_R1            R1(1=A 2=B ) CN @TEST.SCHEMATIC1(sch_1):I00101@ANALOG.R.Normal(chips)
R_R2            R2(1=B 2=N00212 ) CN @TEST.SCHEMATIC1(sch_1):I00125@ANALOG.R.Normal(chips)
R_R3            R3(1=0 2=B ) CN @TEST.SCHEMATIC1(sch_1):I00149@ANALOG.R.Normal(chips)
_    _(A=A)
_    _(B=B)
.ENDALIASES
