.ALIASES
R_R6            R6(1=N02319 2=1 ) CN @TESTPRE.SCHEMATIC1(sch_1):I01972@ANALOG.R.Normal(chips)
V_V3            V3(+=N02319 -=0 ) CN @TESTPRE.SCHEMATIC1(sch_1):I03200@SOURCE.VSIN.Normal(chips)
R_R3            R3(1=3 2=1 ) CN @TESTPRE.SCHEMATIC1(sch_1):I01996@ANALOG.R.Normal(chips)
R_R4            R4(1=0 2=3 ) CN @TESTPRE.SCHEMATIC1(sch_1):I02020@ANALOG.R.Normal(chips)
R_RL            RL(1=2 2=3 ) CN @TESTPRE.SCHEMATIC1(sch_1):I02044@ANALOG.R.Normal(chips)
R_R1            R1(1=1 2=2 ) CN @TESTPRE.SCHEMATIC1(sch_1):I02068@ANALOG.R.Normal(chips)
R_R2            R2(1=2 2=0 ) CN @TESTPRE.SCHEMATIC1(sch_1):I02092@ANALOG.R.Normal(chips)
_    _(1=1)
_    _(2=2)
_    _(3=3)
.ENDALIASES
