.ALIASES
V_V2            V2(+=N00181 -=0 ) CN @ÈÄÚ11.SCHEMATIC1(sch_1):I00246@SOURCE.VDC.Normal(chips)
V_V1            V1(+=N00122 -=0 ) CN @ÈÄÚ11.SCHEMATIC1(sch_1):I00044@SOURCE.VDC.Normal(chips)
R_R1            R1(1=N00122 2=N00152 ) CN @ÈÄÚ11.SCHEMATIC1(sch_1):I00077@ANALOG.R.Normal(chips)
Q_Q1            Q1(c=N00181 b=N00152 e=0 ) CN @ÈÄÚ11.SCHEMATIC1(sch_1):I00116@BIPOLAR.Q2N3904.Normal(chips)
.ENDALIASES
